### ISSUE TITLE
Ionic

### ISSUE THREAD

**Issue by darklord1807** [hakandilek/tsartoolkit#1]
Hello,

I downloaded the source, did npm install and then ionic serve but getting the error: 

Module '"jsartoolkit5"' has no exported member 'ARThreeScene'.

Kindly advise

**Comment by hakandilek** [comment]
thanks for reporting. I've forgotten to updte ref to jsartoolkit. don't forget to npm install after git pull ;)

**Comment by darklord1807** [comment]
Great!Was able to make it work. But it is not detecting the marker. Nothing is happening.

**Comment by hakandilek** [comment]
Did you try with markers ![5](https://raw.githubusercontent.com/artoolkit/artoolkit5/master/doc/patterns/Matrix%20code%203x3%20(72dpi)/5.png) and ![20](https://raw.githubusercontent.com/artoolkit/artoolkit5/master/doc/patterns/Matrix%20code%203x3%20(72dpi)/20.png)?

**Comment by darklord1807** [comment]
Thanks! Working with these markers. I have tried to run it on an android phone.  The frame rate is slow though.  Any idea how it can be optimized?

**Comment by hakandilek** [comment]
Well I haven't paid so much attention on optimization but you'll get a better frame rate if you use 2D html elements instead of 3D objects.
